import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div>
          <title>Game Plus</title>
        </div>
        <div className="Topbanner">
          <Link href="/">Game Plus</Link>
          <Link href="/gamelist">게임</Link>
          <Link href="/store">상점</Link>
          <Link href="/community">커뮤니티</Link>
          <div class="button">
            <Link href="/login"><button>로그인</button></Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}

